export const MONSTERS = {
    godzilla: {
        id: 'godzilla',
        name: 'Godzilla',
        category: 'balanced',
        hp: 100,
        baseDamage: 13,
        speedBonus: 1.0,
        attacks: {
            A: { name: 'Atomic Breath', slot: 'A' },
            B: { name: 'Tail Sweep', slot: 'B' },
            C: { name: 'Nuclear Pulse', slot: 'C' },
        },
    },
    kingkong: {
        id: 'kingkong',
        name: 'King Kong',
        category: 'balanced',
        hp: 100,
        baseDamage: 13,
        speedBonus: 1.0,
        attacks: {
            A: { name: 'Primal Punch', slot: 'A' },
            B: { name: 'Chest Pound', slot: 'B' },
            C: { name: 'Boulder Throw', slot: 'C' },
        },
    },
    gamera: {
        id: 'gamera',
        name: 'Gamera',
        category: 'tank',
        hp: 120,
        baseDamage: 12,
        speedBonus: 0.8,
        attacks: {
            A: { name: 'Plasma Fireball', slot: 'A' },
            B: { name: 'Shell Slam', slot: 'B' },
            C: { name: 'Spinning Jet', slot: 'C' },
        },
    },
    hedorah: {
        id: 'hedorah',
        name: 'Hedorah',
        category: 'tank',
        hp: 120,
        baseDamage: 12,
        speedBonus: 0.8,
        attacks: {
            A: { name: 'Sludge Beam', slot: 'A' },
            B: { name: 'Toxic Cloud', slot: 'B' },
            C: { name: 'Acid Splash', slot: 'C' },
        },
    },
    rodan: {
        id: 'rodan',
        name: 'Rodan',
        category: 'speed',
        hp: 85,
        baseDamage: 12,
        speedBonus: 1.5,
        attacks: {
            A: { name: 'Sonic Dive', slot: 'A' },
            B: { name: 'Wing Gust', slot: 'B' },
            C: { name: 'Beak Strike', slot: 'C' },
        },
    },
    mothra: {
        id: 'mothra',
        name: 'Mothra',
        category: 'speed',
        hp: 85,
        baseDamage: 11,
        speedBonus: 1.6,
        attacks: {
            A: { name: 'Antenna Beam', slot: 'A' },
            B: { name: 'Scale Dust', slot: 'B' },
            C: { name: 'Wing Slash', slot: 'C' },
        },
    },
    anguirus: {
        id: 'anguirus',
        name: 'Anguirus',
        category: 'speed',
        hp: 85,
        baseDamage: 13,
        speedBonus: 1.4,
        attacks: {
            A: { name: 'Thunder Ball', slot: 'A' },
            B: { name: 'Carapace Roll', slot: 'B' },
            C: { name: 'Jaw Crush', slot: 'C' },
        },
    },
    ghidorah: {
        id: 'ghidorah',
        name: 'King Ghidorah',
        category: 'bruiser',
        hp: 85,
        baseDamage: 15,
        speedBonus: 1.0,
        attacks: {
            A: { name: 'Gravity Beam', slot: 'A' },
            B: { name: 'Triple Bite', slot: 'B' },
            C: { name: 'Wing Storm', slot: 'C' },
        },
    },
    mechagodzilla: {
        id: 'mechagodzilla',
        name: 'Mecha Godzilla',
        category: 'charger',
        hp: 100,
        baseDamage: 14,
        speedBonus: 1.0,
        special: 'charge',
        attacks: {
            A: { name: 'Laser Beam', slot: 'A' },
            B: { name: 'Missile Barrage', slot: 'B' },
            C: { name: 'Mecha Slam', slot: 'C' },
        },
    },
};
